name: "Scrapbox Notify"
description: "Notify Scrapbox project updates to Slack and Discord."
inputs:
  feed_url:
    description: Feed URL (e.g. https://scrapbox.io/api/feed/${projectName})
    required: true
  slack_webhook:
    description: Slack Incoming Webhook
    required: false
  discord_webhook:
    description: Discord Incoming Webhook
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
